version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: game_monitoring_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - game_monitoring_api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/game_monitoring_api?schema=public
      JWT_SECRET: fa04aea5e0bf854b72bb9201401e6edf96b95345c3eef52e28eeba7776b335f5
      PORT: 3000
    networks:
      - game_monitoring_api
networks:
  game_monitoring_api: