/* tslint:disable */
/* eslint-disable */
/**
 * User and Team Management API
 * API for user and team management with JWT internal
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {InvitationResponse, PutInvitationRequest,} from '../models';

export interface TeamsTeamIdInvitationsGetRequest {
    teamId: string;
}

export interface TeamsTeamIdInvitationsPostRequest {
    teamId: string;
}

export interface TeamsTeamIdInvitationsPutRequest {
    teamId: string;
    putInvitationRequest: PutInvitationRequest;
}

/**
 * InvitationApi - interface
 *
 * @export
 * @interface InvitationApiInterface
 */
export interface InvitationApiInterface {
    /**
     * Get pending invitations for a team
     */
    teamsTeamIdInvitationsGet(requestParameters: TeamsTeamIdInvitationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InvitationResponse>>;

    /**
     * Request Team membership
     */
    teamsTeamIdInvitationsPost(requestParameters: TeamsTeamIdInvitationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationResponse>;

    /**
     * Accept or reject a user invitation (Team Owner only)
     */
    teamsTeamIdInvitationsPut(requestParameters: TeamsTeamIdInvitationsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationResponse>;

}
