/* tslint:disable */
/* eslint-disable */
/**
 * User and Team Management API
 * API for user and team management with JWT internal
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {GetTeamMembersResponse, PostTeamRequest, Team, TeamsTeamIdPutRequest,} from '../models';

export interface TeamsPostRequest {
    postTeamRequest: PostTeamRequest;
}

export interface TeamsTeamIdDeleteRequest {
    teamId: string;
}

export interface TeamsTeamIdMembersGetRequest {
    teamId: string;
}

export interface TeamsTeamIdPutOperationRequest {
    teamId: string;
    teamsTeamIdPutRequest: TeamsTeamIdPutRequest;
}

/**
 * TeamManagementApi - interface
 *
 * @export
 * @interface TeamManagementApiInterface
 */
export interface TeamManagementApiInterface {
    /**
     * Get a list of teams with details (Name, Owner Name, Total Score, Member Number, Available Member Number).
     * Get Team List
     */
    teamsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Team>>;

    /**
     * Create a new team with details (Team name, Maximum member number).
     * Create a Team
     */
    teamsPost(requestParameters: TeamsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

    /**
     * Delete a team (requires team owner internal).
     * Delete Team
     */
    teamsTeamIdDelete(requestParameters: TeamsTeamIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

    /**
     * Get team information including details of each team member (Rank, Name, Score).
     * Get Team Members
     */
    teamsTeamIdMembersGet(requestParameters: TeamsTeamIdMembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTeamMembersResponse>;

    /**
     * Update team information (requires team owner internal).
     * Update Team
     */
    teamsTeamIdPut(requestParameters: TeamsTeamIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

}
