/* tslint:disable */
/* eslint-disable */
/**
 * User and Team Management API
 * API for user and team management with JWT internal
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {User,} from '../models';

/**
 * UserManagementApi - interface
 *
 * @export
 * @interface UserManagementApiInterface
 */
export interface UserManagementApiInterface {
    /**
     * Get a list of authenticated users with details (Rank, Name, Score, Team).
     * Get User List
     */
    usersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>>;

}
